// `.open-next/worker.js` is a build artifact (generated by `npm run cf:build`,
// gitignored) that worker-entry.ts wraps to add a `scheduled` handler. This
// stub lets that import type-check even before a build has produced the real
// file -- once it exists, TypeScript resolves the real file instead.
declare module "*/.open-next/worker.js" {
  const handler: {
    fetch: (request: Request, env: Env, ctx: ExecutionContext) => Promise<Response>;
  };
  export default handler;
}
